#!/usr/bin/env python3
"""
Setup script to create .env file for development
"""

env_content = """# Game Parlour SaaS - Environment Configuration
# Generated by setup_env.py

# Database
DATABASE_URL=sqlite:///./game_parlour.db

# Security
SECRET_KEY=game-parlour-development-secret-key-change-for-production
ACCESS_TOKEN_EXPIRE_MINUTES=480

# Razorpay (Replace with your actual keys)
RAZORPAY_KEY_ID=rzp_test_frWcC85VwYGHuv
RAZORPAY_KEY_SECRET=your-razorpay-secret-key-here

# App Settings
ENVIRONMENT=development
DEBUG=True
ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000

# Email (Optional - for notifications)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=

# Frontend URL
FRONTEND_URL=http://localhost:3000
"""

def create_env_file():
    """Create .env file if it doesn't exist"""
    import os
    
    env_file = ".env"
    
    if os.path.exists(env_file):
        print(f"⚠️  {env_file} already exists. Backing up to {env_file}.backup")
        os.rename(env_file, f"{env_file}.backup")
    
    with open(env_file, "w") as f:
        f.write(env_content)
    
    print(f"✅ Created {env_file}")
    print("\n📝 Next steps:")
    print("1. Edit .env file and add your Razorpay secret key")
    print("2. Run: python main.py")
    print("\n🔑 Get your Razorpay secret key from:")
    print("   https://dashboard.razorpay.com/app/keys")

if __name__ == "__main__":
    create_env_file()
